version: '3.8'

services:
  proxy:
    build: ./proxy
    container_name: proxy
    environment:
      - WEB_INTEGRATION_ID= # Your web integration ID
      - QLIK_TENANT_ID= # Your Qlik tenant ID like "EXAMPLE.us.qlikcloud.com"
      - PROXY_URL= # Your proxy URL like "proxy.EXAMPLE.com"
      - LOCALHOST_AVAIABLE=True # Set to False if you are running in production
      - MASHUP_PORT=  # Port where the mashup is running
      - MASHUP_DOMAIN= # Domain where the mashup is running like app.EXAMPLE.com
    ports:
      - "9000:9000"
    volumes:
      - ./proxy:/proxy
    networks:
      - app_network

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - proxy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge